/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.customcomponents;

import java.awt.Color;
import java.awt.Component;

import javax.swing.JFrame;

/**
 *
 * @author maima
 */
public class AFChatItem extends javax.swing.JPanel {

    public static void main(String[] args){
        JFrame frame = new JFrame();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setBounds(100, 100, 800, 600);
        frame.setLayout(null);
        AFChatItem chat = new AFChatItem();
        chat.setLocation(0, 0);
        chat.setSize(500, 300);
        chat.hideLeft();
        chat.setMessage("alodslfdos");
        chat.setBackground(new Color(255, 0 ,0));
        chat.setVisible(true);
        frame.add(chat);
        frame.setVisible(true);

    }

    public void changeTextUpload(byte percent){
        //TODO change text upload
    }

    /**
     * Creates new form AFChatItem
     */
    public AFChatItem() {
        initComponents();
    }
    public void setMessage(String mess)
    {
        TextBody.add(new javax.swing.JLabel(mess));
        TextBody1.add(new javax.swing.JLabel(mess));
    }
    public void hideLeft()
    {
        PanelBodyLeft.setVisible(!PanelBodyLeft.isVisible());
        TopPanel.setAlignmentX(Component.RIGHT_ALIGNMENT);
    }
    public void hideRight()
    {
        PanelBodyRight.setVisible(!PanelBodyRight.isVisible());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TopPanel = new javax.swing.JPanel();
        PanelBodyLeft = new javax.swing.JPanel();
        TextBody = new MessagePanel();
        PanelButton = new javax.swing.JPanel();
        ButtonCopy = new javax.swing.JButton();
        ButtonDelete = new javax.swing.JButton();
        PanelBodyRight = new javax.swing.JPanel();
        TextBody1 = new MessagePanel();
        BottomPanel = new javax.swing.JPanel();
        LabelAuthor = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(773, 160));

        TopPanel.setPreferredSize(new java.awt.Dimension(749, 132));
        TopPanel.setLayout(new javax.swing.BoxLayout(TopPanel, javax.swing.BoxLayout.LINE_AXIS));

        PanelBodyLeft.setMinimumSize(new java.awt.Dimension(290, 100));

        /*
        TextBody.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextBodyActionPerformed(evt);
            }
        });
        */

        javax.swing.GroupLayout PanelBodyLeftLayout = new javax.swing.GroupLayout(PanelBodyLeft);
        PanelBodyLeft.setLayout(PanelBodyLeftLayout);
        PanelBodyLeftLayout.setHorizontalGroup(
            PanelBodyLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBodyLeftLayout.createSequentialGroup()
                .addComponent(TextBody, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        PanelBodyLeftLayout.setVerticalGroup(
            PanelBodyLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TextBody)
        );

        TopPanel.add(PanelBodyLeft);

        PanelButton.setMinimumSize(new java.awt.Dimension(290, 100));

        ButtonCopy.setBackground(new java.awt.Color(255, 255, 255));
        ButtonCopy.setForeground(new java.awt.Color(255, 255, 255));

        ButtonDelete.setBackground(new java.awt.Color(255, 255, 255));
        ButtonDelete.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelButtonLayout = new javax.swing.GroupLayout(PanelButton);
        PanelButton.setLayout(PanelButtonLayout);
        PanelButtonLayout.setHorizontalGroup(
            PanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelButtonLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(ButtonCopy, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        PanelButtonLayout.setVerticalGroup(
            PanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonCopy, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        TopPanel.add(PanelButton);

        PanelBodyRight.setMinimumSize(new java.awt.Dimension(290, 100));

        /*
        TextBody1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextBody1ActionPerformed(evt);
            }
        });
        */

        javax.swing.GroupLayout PanelBodyRightLayout = new javax.swing.GroupLayout(PanelBodyRight);
        PanelBodyRight.setLayout(PanelBodyRightLayout);
        PanelBodyRightLayout.setHorizontalGroup(
            PanelBodyRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBodyRightLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(TextBody1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE))
        );
        PanelBodyRightLayout.setVerticalGroup(
            PanelBodyRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TextBody1, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
        );

        TopPanel.add(PanelBodyRight);

        LabelAuthor.setText("Time-Date");

        javax.swing.GroupLayout BottomPanelLayout = new javax.swing.GroupLayout(BottomPanel);
        BottomPanel.setLayout(BottomPanelLayout);
        BottomPanelLayout.setHorizontalGroup(
            BottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BottomPanelLayout.createSequentialGroup()
                .addComponent(LabelAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        BottomPanelLayout.setVerticalGroup(
            BottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BottomPanelLayout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addComponent(LabelAuthor))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
                    .addComponent(BottomPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(BottomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TextBody1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextBody1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextBody1ActionPerformed

    private void TextBodyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextBodyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextBodyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BottomPanel;
    private javax.swing.JButton ButtonCopy;
    private javax.swing.JButton ButtonDelete;
    private javax.swing.JLabel LabelAuthor;
    private javax.swing.JPanel PanelBodyLeft;
    private javax.swing.JPanel PanelBodyRight;
    private javax.swing.JPanel PanelButton;
    private MessagePanel TextBody;
    private MessagePanel TextBody1;
    private javax.swing.JPanel TopPanel;
    // End of variables declaration//GEN-END:variables
    public void startTimer(String file, long size) {
        //TODO start timer
    }
}
